### ISSUE TITLE
'x' has been coerced to a factor - ERROR message despite "x" being a factor variable

### ISSUE THREAD

**Issue by laujohns** [matthewwolak/ICC#2]
Hello,

I converted my "id" variable from integer to factor variable and still receive the following message, "'x' has been coerced to a factor"...any ideas why?

Here's my code:

id<-as.factor(id)
class(id)
ICCest (id, log_tsh, data=aim2_long, alpha=0.05, CI.type=c("THD"))

**Comment by matthewwolak** [comment]
This is a scoping issue with the code provided to change `id` to a `factor` variable in R. In the example code, the variable `id` in the `data.frame` has not been converted to a factor, only an R object that exists as and independent object outside of the `data.frame`. Therefore, when running the line `ICCest (id, log_tsh, data=aim2_long, alpha=0.05, CI.type=c("THD"))` the function uses standard evaluation rules to first look in the object passed to the `data` argument (e.g., 'aim2_long') for the variable `id`. Since I assume such a column exists, then the function uses that. 

I suspect that was the conclusion when the issue was closed, but hope this adds more details/clarity.
